version: '3.8'
services:
  front-despacho:
    build:
      context: .
      args:
        - VITE_API_URL_VENTAS=http://${BACKEND_HOST}:8080
        - VITE_API_URL_DESPACHOS=http://${BACKEND_HOST}:8081
    ports:
      - "80:80"
