FROM mysql:8.0

# Podríamos agregar scripts de inicialización .sql en /docker-entrypoint-initdb.d/ si los tuviéramos
# Por ahora, usamos la imagen base oficial para asegurar compatibilidad total con Spring Boot

ENV MYSQL_DATABASE=ventasdb
ENV MYSQL_ROOT_PASSWORD=root
