name: Deploy DB Service

on:
  push:
    branches: [ deploy ]
    paths:
      - 'db/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Deploy to DB EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DB }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/innovatech_stack
            cd ~/innovatech_stack
            # git pull origin deploy
            cd db
            sudo docker-compose down || true
            sudo docker-compose up -d
